---
# HTTPRoute para Agent SDK
# Path: /agent-sdk/* → /*
# Rate: 15 rps, Timeout: 240s
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: agent-sdk-httproute
  namespace: orbix
spec:
  parentRefs:
  - name: main-gateway
    namespace: traefik-system
  hostnames:
  - "homolog-agent.nddorbix.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /agent-sdk/
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: agent-sdk-middleware
    backendRefs:
    - name: agent-sdk-service
      port: 80
